name: Branch Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  setup:
    name: Set up jobs
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Merge with master
      - name: Merge with master
        run: ORIG_BRANCH=$(git rev-parse --abbrev-ref HEAD); (git checkout master || git checkout -b master) && git pull origin master && git merge $ORIG_BRANCH
      # Cache node_modules and refresh the cache only when package-lock.son changes
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # Install dependencies
      - name: Install dependencies
        run: npm install
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Merge with master
      - name: Merge with master
        run: ORIG_BRANCH=$(git rev-parse --abbrev-ref HEAD); (git checkout master || git checkout -b master) && git pull origin master && git merge $ORIG_BRANCH
      # Install dependencies
      - name: Install dependencies
        run: npm install
      # Runs ESLint
      - name: Run ESLint
        run: npm run lint .
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Merge with master
      - name: Merge with master
        run: ORIG_BRANCH=$(git rev-parse --abbrev-ref HEAD); (git checkout master || git checkout -b master) && git pull origin master && git merge $ORIG_BRANCH
      # Install dependencies
      - name: Install dependencies
        run: npm install
      # Runs unit tests
      - name: Run unit tests
        run: npm run test
