name: Branch Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  setup:
    name: Set up jobs
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Runs ESLint
      - name: Run ESLint
        run: npm run lint .
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Runs unit tests
      - name: Run unit tests
        run: npm test
