name: Branch Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      # Runs ESLint
      - name: Run ESLint
        run: npm run lint .
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      # Runs unit tests
      - name: Run unit tests
        run: npm test
